---
- name: Otus ansible
  hosts: all
  become: true

  vars:
    NGINX_PORT: 8080

  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: installed
      notify: restart nginx

    - name: Template nginx index page
      template:
        src: index.html.j2
        dest: "/usr/share/nginx/html/index.html"
      notify: restart nginx

    - name: Template nginx default.conf
      template:
        src: default.conf.j2
        dest: "/etc/nginx/conf.d/default.conf"
      notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
        enabled: true
      register: restart_status
      until: restart_status is succeeded
