# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "ansible-server" do |server|
      config.vm.box = 'centos/7'
      config.vm.box_version = "1804.02"
  
      config.ssh.insert_key = 'false'
    
      server.vm.host_name = 'ansible-server'
      server.vm.network :private_network, ip: "192.168.56.101" 
      server.vm.network "forwarded_port", guest: 8080, host: 8080

      server.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
        end
     

        config.vm.provision "ansible_local" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.playbook = "playbook.yml"
          ansible.become = "true"
        end

      end
    
    
    end