# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "bootloader-server" do |server|
      config.vm.box = 'centos/7'
      config.vm.box_version = "1804.02"
  
      config.ssh.insert_key = 'false'
    
      server.vm.host_name = 'bootloader-server'
      server.vm.network :private_network, ip: "192.168.56.101" 
      
      server.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.cpus = 2
        vb.customize ["modifyvm", :id, "--vram", "128"]
      end
     
      server.vm.provision "shell",
      name: "task_2",
      privileged: true,
      path: "task_2.sh"

      server.vm.provision "shell",
      name: "task_3",
      privileged: true,
      path: "task_3.sh"

      end
    
    
    end