---
- name: Otus ansible
  hosts: all
  become: true

  tasks:
    - name: provisioner info
      ansible.builtin.debug:
        msg: "Hi otus -task 18  {{ inventory_hostname }}"

    - name: add default gateway for ofiice 2 Router
      lineinfile:
        dest: /etc/sysconfig/network-scripts/ifcfg-eth1
        line: GATEWAY=192.168.1.1
      notify:
        - restart network

    - name: add routes
      template:
        src: "{{ inventory_hostname }}/{{  item  }}"
        dest: /etc/sysconfig/network-scripts/
      loop:
        - route-eth1

  handlers:
    - name: restart network
      service:
        name: network
        state: restarted
