 # -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

    config.vm.box = "centos/7"
    config.vm.synced_folder ".", "/vagrant", type: "rsync"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = "2"
      end


    config.vm.define "server" do |server|
      server.vm.hostname = "server.loc"
      server.vm.network "private_network", ip: "192.168.10.10"
    end
    config.vm.define "client" do |client|
      client.vm.hostname = "client.loc"
      client.vm.network "private_network", ip: "192.168.10.20"
    end
  
    config.vm.provision "base", type: "ansible_local" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "provisioners/base.yml"
        ansible.become = "true"
    end    
    
    config.vm.provision "openvpn", type: "ansible_local" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "provisioners/openvpn.yml"
        ansible.become = "true"
        ansible.extra_vars = {
            tun_type:  'tap'
          }

    end


    config.vm.provision "rasvpn", type: "ansible" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "provisioners/rasvpn.yml"
        ansible.become = "true"
    end


  end
     