---
- name: Otus ansible
  hosts: all
  become: true

  tasks:

    - name: provisioner info 
      ansible.builtin.debug:
        msg: "Hi otus - task 25 {{ ansible_host }}"

    - name: Include vars
      ansible.builtin.include_vars:
        file: main

    - name: Add FQDN entries to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      loop:
        - '{{ ipa_server_ip }} {{ ipa_server_fqdn }} {{ ipa_server_fqdn }}'
        - '{{ ipa_client_ip }} {{ ipa_client_fqdn }} {{ ipa_client_fqdn }}'


    - name: Set FQDN hostname
      hostname:
        name: '{{ ipa_server_fqdn }}'

    - name: start and enable firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: configure firewalld service
      firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: yes
      loop:
        - http
        - https

    - name: configure firewalld port's
      firewalld:
        port: "{{  item  }}"
        state: enabled
        permanent: yes
      loop:
        - 389/tcp
        - 88/tcp
        - 464/tcp
        - 464/udp
        - 123/udp

    - name: reload firewall
      shell: firewall-cmd --reload

    - name: install ipa-server
      yum:
        name: "{{  item  }}"
        state: latest
      loop:
        - nss
        - ipa-server
        - ipa-server-dns
        - bind-dyndb-ldap

    - name: init ipa-server
      command:
        cmd: |
          ipa-server-install -U
          --realm {{ ipa_realm }}
          --domain {{ ipa_domain }}
          --hostname={{ ipa_server_fqdn }}
          --ip-address={{ ipa_server_ip }}
          --setup-dns
          --auto-forwarders
          --no-reverse
          --mkhomedir
          -a {{ ipa_server_pass }}
          -p {{ ipa_server_pass }}
        creates: /etc/ipa/default.conf

    - name: Add firewalld ipa service
      shell: |
        firewall-cmd --add-service=freeipa-ldap --add-service=freeipa-ldaps &&
        firewall-cmd --add-service=freeipa-ldap --add-service=freeipa-ldaps --permanent
