global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

remote_write:
  - url: http://localhost:8428/api/v1/write

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
  - job_name: node
    static_configs:
     - targets:
       - localhost:9100 
