# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "pam-server" do |server|
      config.vm.box = "almalinux/8"
      config.vm.box_version = "8.6.20221001"
      config.vm.synced_folder ".", "/vagrant", type: "rsync"
      config.ssh.insert_key = 'false'
    
      server.vm.host_name = 'pam-server'
      server.vm.network :private_network, ip: "192.168.56.101" 

      server.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end
        
        config.vm.provision "ansible_local" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.playbook = "playbook.yml"
          ansible.become = "true"
        end

      end    
    
    end