---
- name: Otus ansible
  hosts: all
  become: true

  vars:
    router_id_enable: false
    # symmetric_routing: false


  tasks:
 
    - name: Include vars
      ansible.builtin.include_vars:
        file: "{{ ansible_host }}"

    - name: set up OSPF
      template:
        src: frr.conf.j2
        dest: /etc/frr/frr.conf
        owner: frr
        group: frr
        mode: 0640
      notify:
      - restart FRR

    - name: set up asynchronous routing
      sysctl:
        name: net.ipv4.conf.all.rp_filter
        value: '0'
        state: present


  handlers:
    - name: restart FRR
      service:
        name: frr
        state: restarted
        enabled: true
