---
- name: Otus ansible
  hosts: all
  become: true

  vars:
    router_id_enable: false
    symmetric_routing: empty


  tasks:

    - name: Include vars
      ansible.builtin.include_vars:
        file: "{{ ansible_host }}"

    - name: install base tools
      apt:
        name:
        - vim
        - traceroute
        - tcpdump
        - net-tools
        state: present
        update_cache: true

    - name: disable ufw service
      service:
        name: ufw
        state: stopped
        enabled: false

    - name: add gpg frrouting.org
      apt_key:
        url: "https://deb.frrouting.org/frr/keys.asc"
        state: present

    - name: add frr repo
      apt_repository:
        repo: 'deb https://deb.frrouting.org/frr {{ ansible_distribution_release }} frr-stable'
        state: present

    - name: install FRR packages
      apt:
        name:
        - frr
        - frr-pythontools
        state: present
        update_cache: true


    - name: set up forward packages across routers
      sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present

    - name: base set up OSPF
      lineinfile: 
        path: /etc/frr/daemons
        regexp: '^(.*)ospfd=no(.*)$'
        line: 'ospfd=yes'
        backrefs: yes

    - name: set up OSPF
      template:
        src: frr.conf.j2
        dest: /etc/frr/frr.conf
        owner: frr
        group: frr
        mode: 0640
      notify:
      - restart FRR


  handlers:
    - name: restart FRR
      service:
        name: frr
        state: restarted
        enabled: true
