---
- name: Otus ansible
  hosts: all
  become: true


  tasks:
    - name: provisioner info 
      ansible.builtin.debug:
        msg: "Hi otus -task 24  {{ inventory_hostname }}"


    - name: set vlan100 config
      copy:
        src: "{{ inventory_hostname }}/ifcfg-vlan100"
        dest: /etc/sysconfig/network-scripts/
        owner: root
        group: root
        mode: 644
      notify:
        - restart network

  handlers:
    - name: restart network
      service:
        name: network
        state: restarted