---
- name: Otus ansible
  hosts: all
  become: true

  tasks:
    - name: provisioner info
      ansible.builtin.debug:
        msg: "Hi otus -task 20  {{ inventory_hostname }}"

    - name: add default gateway for centralRouter
      lineinfile:
        dest: /etc/sysconfig/network-scripts/ifcfg-eth1
        line: GATEWAY=192.168.255.1
      notify:
        - restart network

    - name: add routes
      template:
        src: "centralRouter/{{  item  }}"
        dest: /etc/sysconfig/network-scripts/
      loop:
        - route-eth1
        - route-eth3
        # - route-eth6
      notify:
        - restart network

  handlers:
    - name: restart network
      service:
        name: network
        state: restarted
