---
- name: Otus ansible
  hosts: all
  become: true

  tasks:
    - name: provisioner info
      ansible.builtin.debug:
        msg: "Hi otus -task 20  {{ inventory_hostname }}"

    - name: install iptables service
      yum:
        name: [ 'iptables', 'iptables-services', 'firewalld']
        state: present
        update_cache: true

    - name: copy iptables config to InetRouter
      template:
        src: inetRouter/internetRouter.iptables.conf.j2
        dest: /etc/sysconfig/iptables
        owner: root
        group: root
        mode: 0600

    - name: add routes
      template:
        src: "inetRouter/{{  item  }}"
        dest: /etc/sysconfig/network-scripts/
      loop:
        - route-eth1
      notify:
        - restart network

    - name: start and enable iptables service
      service:
        name: iptables
        state: restarted
        enabled: true

    - name: "firewall-cmd --zone=external --change-interface=eth0 --permanent"
      ansible.posix.firewalld:
        zone: external
        interface: eth0
        permanent: yes
        state: enabled

    - name: "firewall-cmd --zone=external --change-interface=eth2 --permanent"
      ansible.posix.firewalld:
        zone: external
        interface: eth2
        permanent: yes
        state: enabled

  handlers:
    - name: restart network
      service:
        name: network
        state: restarted
