# -*- mode: ruby -*-
# vim: set ft=ruby :
MACHINES = {
:inetRouter => {
        :box_name => "centos/7",
         :net => [
                 {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                ]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :net => [
            {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
            {ip: '192.168.0.1',   adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
            {ip: '192.168.255.9', adapter: 4, netmask: "255.255.255.252",virtualbox__intnet: "router2-net"}
            ]
  },  
  :centralServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
                ]
  },
  :inetRouter2 => {
    :box_name => "centos/7",
    :vm_name => "inetRouter2",
    :net => [
      {ip: '192.168.255.10', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router2-net"},
 
    ]
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
        box.vm.synced_folder ".", "/vagrant", type: "rsync"

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        if boxconfig[:vm_name] == "inetRouter2"
          box.vm.network "forwarded_port", guest: 8080, host: 9192, host_ip: "127.0.0.1", id: "http"
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
 
        box.vm.provision "ansible_local" do |ansible|
         ansible.galaxy_role_file = "provisioners/requirements.yml"
         ansible.galaxy_command = "ansible-galaxy collection install -fr  %{role_file} "
         ansible.galaxy_roles_path = '/etc/ansible/roles'

          ansible.playbook = "provisioners/common.yml"
          ansible.become = "true"
        end        
        
        box.vm.provision "ansible_local" do |ansible|
          ansible.compatibility_mode = "2.0"
          ansible.playbook = "provisioners/#{boxname.to_s}.yml"
          ansible.become = "true"
        end

        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end 
      end
  end
end